trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'one-configurator-core'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onec-docker-dev.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: '1.1.700-oc-core'
- task: Docker@2
  inputs:
    repository: 'hts2-onec-docker-dev.jfrog.io/$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onec-docker-dev.jfrog.io/one-configurator-core:$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false
    projectKey: 'onec'
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onec-docker-dev.jfrog.io/one-configurator-core:latest'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false
    projectKey: 'onec'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'hts-latest'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'onec'
- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'hts-latest'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'onec'
    targetRepo: 'onec-docker-prod'
    status: 'Released'
    sourceRepo: 'onec-docker-dev'
    includeDependencies: true
    copy: true
    dryRun: false