# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'one-configurator-core'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: JFrogBuildPromotion@1
  inputs:
    artifactoryConnection: 'hts-latest'
    buildName: 'one-configurator'
    buildNumber: '1.1.709-oc-core'
    projectKey: 'onec'
    targetRepo: 'onec-docker-prod'
    status: 'Released'
    sourceRepo: 'onec-docker-dev'
    includeDependencies: true
    copy: true
    dryRun: false

