# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'one-configurator-core'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'jfrog-platform'
    command: 'jf rt dl generic-local/jfrog-artifactory-pro-7.41.6.rpm'

