trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'one-configurator'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onec-docker-dev.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: '1.1.708-oc-core'
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onec-docker-dev.jfrog.io/one-configurator:1.1.708-oc-core'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '1.1.708-oc-core'
    threads: '3'
    skipLogin: false
    projectKey: 'onec'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'hts-latest'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '1.1.708-oc-core'
    projectKey: 'onec'