trigger:

- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'one-configurator-core'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onec-docker-dev.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onec-docker-dev.jfrog.io/one-configurator-core:$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false
    projectKey: 'onec'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'hts-latest'
    buildName: 'one-configurator'
    buildNumber: '1.1.667-oc-core'
    projectKey: 'onec'