trigger:

- master
jobs:
- job: job1
  pool:
    vmImage: 'Ubuntu-18.04'
  variables:
    imageName: 'one-configurator'
steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onc-docker-source.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onc-docker-source.jfrog.io/one-configurator:$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false
    projectKey: 'onc'
- job: job2
  pool:
    vmImage: 'Ubuntu-18.04'
  variables:
    imageName: 'one-configurator-core'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts-latest'
    cliInstallationRepo: 'jfrog-cli-v2-new'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: hts2-onc-docker-source.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: JFrogDocker@1
  inputs:
    command: 'Push'
    artifactoryConnection: 'hts-latest'
    imageName: 'hts2-onc-docker-source.jfrog.io/one-configurator:$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    threads: '3'
    skipLogin: false
    projectKey: 'onc'