name: build docker images

on:
  push:
    branches:
      - 'sekhar-test-buildx-issue'

    paths:
      - 'platform/docker/**'
      - '.github/workflows/docker_images.yaml'   - remved this from actions

# This workflow contains a single job called "docker" which builds and pushes the docker
# images contained in the path platform/docker/images to the JFrog registry.
# it leverages the matrix build strategy to build and push all images in the path.
# we use the paths-filter action to only build and push images that have changed.

# to add a new image, create a new folder in the path platform/docker/images and add a
# Dockerfile to it. The name of the folder will be the name of the image.
# then add the name of the folder to the matrix.image list below.

jobs:
  docker:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: mckinsey-sample-test-docker.jfrog.io
          username: ${{ secrets.SEKHAR_USER }}
          password: ${{ secrets.SEKHAR_PASS }}
      - name: Grab image version
        id: image_version
        run: |
          echo "::set-output name=version::$(cat platform/docker/images/${{ matrix.image }}/VERSION)"
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: platform/docker/images/${{ matrix.image }}
          push: true
          tags: |
            mckinsey-sample-test-docker.jfrog.io/${{matrix.image}}:v1
          # driver: docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
